apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-installer
  namespace: wazuh
spec:
  selector:
    matchLabels:
      job: wazuh-installer
  template:
    metadata:
      labels:
        job: wazuh-installer
    spec:
      hostPID: true
      restartPolicy: Always
      containers:
      - image: anjuls/wazuh-installer:1.0
        imagePullPolicy: Always
        name: wazuh-installer
        env:
          - name: WORKER_IP
            value: "10.0.0.34"
          - name: MANAGER_IP
            value: "10.0.0.40"
        securityContext:
          privileged: true
        volumeMounts:
        - name: install-script
          mountPath: /tmp
        - name: host-mount
          mountPath: /host
      volumes:
      - name: install-script
        configMap:
          name: wazuh-installer-config
      - name: host-mount
        hostPath:
          path: /var